VDA5050_EN_V1.md

This corrects some minor spelling errors I found in the prose.

Fix some typos in the prose

---

.gitignore
VDA5050_EN_V1.md

Lukas schwarz ds issue 4

---

VDA5050_EN_V1.md

because this type is also used in the nodestate sequenceID

change to integer

---

VDA5050_EN_V1.md

you are note able to get 0.1 kg if you use an integer type to represent the weight

fix weight comment

---

VDA5050_EN.md

Added the first concept of the map update and map status to the VDA 5050. Implemented the concept of mapId in combination with an optional mapVersion.

Added updated map concept using mapId and mapVersion

---

README.md

Revert "Small typo on README.md"

---

VDA5050_EN.md

Fix typo in operation mode description (#94)

---

json_schemas/factsheet.schema

factsheet.json should now be correct (resolving Issue  #153 and Pull Request #123)

Added properties to the whole factsheet and to the maxArrayLens 

---

json_schemas/factsheet.schema

Added properties to the whole factsheet and to the maxArrayLens object according to Issue  #153 and Pull Request #123

Fixed properties issue in factsheet.json

---

json_schemas/order.schema
json_schemas/state.schema

Changed theta to not required in state.schema and fixed typo allowedDeviationXy to allowedDeviationXY in order.schema

Fixed typos in json schemas

---

json_schemas/factsheet.schema

Fixed typo in enum PHYSICAL_LINDE_GUIDED to PHYSICAL_LINE_GUIDED

---

VDA5050_EN.md

Revert "Fix of typo in VDA5050_EN.md"

---

VDA5050_EN.md
json_schemas/factsheet.schema

Added clarification on JSON datatypes Issue #143
Consistent notation of ranges at ultiple intances following Issue #142
Fixed wrong json object name in factsheet.schema, in opposition to PullRequest #161
typo in lastNodeSequenceId description Issue #138
Removed comment on default value using "0" as default, since this can be a valid Sequence Id fixed typo in description of actionParameters.resultDescription according to Issue #136
Fixed multiple instances of AVGs to AGVs Issue #129

Fixed multiple bugs for several issues.

---

VDA5050_EN.md

Fixed a bug that prevented the use of links in the table of contents. Also, the tags that are no longer needed have been removed from all headings.

Updated Table of Contents

---

VDA5050_EN.md

visualization fix chapter reference

visualization fix chapter reference

---

VDA5050_EN.md

fixed wrong table header in chapter 6.12

Fixed Table Header

---

VDA5050_EN.md

- change must --> shall
- URL in download map is mandatory (according to the text), then the parameter is not optional
- fix table of content (links)
- add some clarification to the maximum message length
- ...

Fixes to dev/2.1.0 rc1

---

VDA5050_EN.md

Updated markdown document to version 2.1.0 by removing release candidate hint.

Updated markdown document to version 2.1.0

---

json_schemas/connection.schema
json_schemas/factsheet.schema
json_schemas/instantActions.schema
json_schemas/order.schema
json_schemas/state.schema
json_schemas/visualization.schema

Fixed typos and bugs in the JSOn schemas. No changes were made to the released document.

Updated JSON schemas for Version 2.0.0 to fix existing bugs.

---

json_schemas/factsheet.schema
json_schemas/order.schema
json_schemas/state.schema

Some schema corrections
- missing PAUSE
- typos
- array of enums

Schema corrections

---

VDA5050_EN.md
json_schemas/state.schema

- Added batteryCurrent as an optional field to the state message

Added battery current to the state message

---

VDA5050_EN.md

Added orderId to cancelOrder as an optional variable.

Add orderId to cancelOrder

---

VDA5050_EN.md

This new operating mode was created to give mobile robots the possibility to report a state, where the vehicle’s state message might not be trustworthy and no orders shall be sent.

Added new Operating mode STARTUP.

---

VDA5050_EN.md

Discussion in core team meeting 2025-07-03: The project-specific coordinate system shall be defined for the interaction between mobile robot and master control.

Rework: Project-specific coordinate system definition

---

VDA5050_EN.md

Instant action for setting certificates
